# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.import java.util.*;
public class Bank{
  public static void main (String [] arga){
    
    /**********************************
      
    ENTER YOUR CHOICE (A, B, C, D)
    
    **********************************/

    Scanner scan = new Scanner(System.in);
    
    long nebal = 0;
    System.out.println("A. Check Balance");
    System.out.println("B. Deposit");
    System.out.println("C. Withdraw");
    System.out.println("D. Exit\n");
    System.out.println("*********************************\n");
    
    
    while(true){
    
    System.out.print("Enter choice: ");
    String digit = scan.next();
    System.out.println("");
      
    
    if(digit.equalsIgnoreCase("a")){
      
      System.out.println("••••••••••••••••••••••••");
      System.out.println("Balance = "+"₹"+nebal);
      System.out.println("••••••••••••••••••••••••\n");
      System.out.println("*********************************\n");
    }
     else if(digit.equalsIgnoreCase("b")){
      
      System.out.print("Enter amount: ");
      long amount = scan.nextLong();
      
      if(amount<=0){
        System.out.println("");
        System.out.println("•••••••••••••••••••••••••••••••••");
        System.out.println("NOTE = Please enter valid amount");
        System.out.println("•••••••••••••••••••••••••••••••••");
        System.out.println("");
        System.out.println("*********************************\n");
      }else{
      nebal = amount+nebal;
      System.out.println("");
      System.out.println("••••••••••••••••••••••••••••••••••••••");
      System.out.println("NOTE = ₹"+amount+" successfully added to\nyour account.");
      System.out.println("••••••••••••••••••••••••••••••••••••••");
      System.out.println("");
      System.out.println("*********************************\n");
    
    }
    }
    else if(digit.equalsIgnoreCase("c")){
     
      System.out.print("Enter amount: ");
      long amount1 = scan.nextLong();
      System.out.println("");
      
      if(amount1<=0){
      System.out.println("•••••••••••••••••••••••••••••••••••••••••");
        System.out.println("NOTE = Please enter valid amount");
        System.out.println("•••••••••••••••••••••••••••••••••••••");
        System.out.println("");
      System.out.println("*********************************\n");
      }
      else if (amount1>nebal){       
      System.out.println("•••••••••••••••••••••••••••••••••••••");
      System.out.println("You don't have sufficient balance.\nAdd money by entering \"B\"");
      System.out.println("•••••••••••••••••••••••••••••••••••••");
      System.out.println("");
      System.out.println("*********************************\n");
    }
    else{
      long amo = nebal-amount1;
      System.out.println("•••••••••••••••••••••••••••••••••••••••••");
      System.out.println("NOTE = Your A/C has a withdrawal of Rs."+amount1);
      System.out.println("Check available balance by entering \"A\"");
      System.out.println("•••••••••••••••••••••••••••••••••••••••••");    
      nebal = nebal-amount1;    
      System.out.println("");
      System.out.println("*********************************\n");   
    }      
  }
  else if (digit.equalsIgnoreCase("d")){
     
      System.out.println("Thanks for using our service");
      System.out.println("");
      System.out.println("*********************************\n");
      break;
      }  
      else{
        System.out.println("•••••••••••••••••••••••••••••••");
        System.out.println("Invalid Input.\nEnter choice from (A, B, C, D)");
        System.out.println("•••••••••••••••••••••••••••••••");
        System.out.println("");
        System.out.println("*********************************\n");
      }
      
    }
  }
}
